wsg50_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

gripper_controller:
  type: effort_controllers/GripperActionController
  joint: wsg50_finger_right_joint
  pid: {p: 100, i: 0.5, d: 10.0}
    #wsg50_finger_left_joint: {p: 100, i: 0.5, d: 10.0}
  # type: position_controllers/GripperActionController
  # joint: wsg50_gripper_left_joint
  # pid: {p: 100, i: 0.5, d: 10.0}
